const performanceEquipmentLabels = <String, String>{
  'stable_support': 'apoyo estable',
  'weighted_vest': 'chaleco lastrado',
  'barbell': 'barra',
  'bench': 'banco',
  'plates': 'discos',
  'rack': 'rack',
  'dumbbell': 'mancuerna',
  'dumbbell_pair': 'dos mancuernas',
  'adjustable_bench': 'banco regulable',
  'chest_press_machine': 'máquina de press de pecho',
  'shoulder_press_machine': 'máquina de press de hombros',
  'landmine_anchor': 'anclaje landmine',
  'pull_up_bar': 'barra de dominadas',
  'neutral_grip_bar': 'barra con agarre neutro',
  'resistance_band': 'banda de asistencia',
  'assisted_pull_up_machine': 'máquina de dominadas asistidas',
  'dip_belt': 'cinturón de lastre',
  'lat_pulldown_machine': 'máquina de jalón',
  'cable_row_machine': 'polea de remo',
  'row_machine': 'máquina de remo de fuerza',
  'climbing_rope': 'cuerda de trepa',
  'anchored_rope': 'cuerda anclada',
  'leg_press_machine': 'prensa de piernas',
  'stable_step': 'escalón estable',
  'trap_bar': 'barra hexagonal',
  'leg_curl_machine': 'máquina de curl femoral',
  'nordic_anchor': 'anclaje para nordic',
  'cable_machine': 'polea',
  'stable_box': 'cajón estable',
  'cones': 'conos',
  'measuring_tape': 'cinta métrica',
  'external_cue': 'señal externa',
  'medicine_ball': 'balón medicinal',
  'kettlebell': 'kettlebell',
  'tennis_ball': 'pelota de tenis',
  'chalk': 'tiza',
};

String performanceEquipmentLabel(String code) =>
    performanceEquipmentLabels[code] ?? code.replaceAll('_', ' ');
